version: '3.8'

services:
  todo-app:
    image: surajkk93/todo-app:0.1
    ports:
      - "5000:5000"    # Expose port 5000 for your app
    deploy:
      replicas: 1   # Adjust the number of replicas as needed
      restart_policy:
        condition: on-failure
    networks:
      - todo-network

networks:
  todo-network:
