apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: surajkk93/todo-app:latest  # Your Docker Hub image
        ports:
        - containerPort: 2000  # The port your app is running on
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 2000  # Exposing port 80
    targetPort: 2000  # The port your app listens to inside the container
  selector:
    app: todo-app
